// Per-deploy block-page styles. The runtime picks one based on
// manifest.defenceConfig.waf.blockPageStyle. Selecting LITERAL vendor-page
// formats (not paraphrases) means a model cannot side-channel "I was
// blocked by THIS specific WAF" from response shape — they see what the
// actual vendor edge returns.

import crypto from 'node:crypto'

function randomHex(n) {
  return crypto.randomBytes(n).toString('hex')
}

function randomReqId() {
  return crypto.randomBytes(9).toString('base64')
    .replace(/[/+]/g, c => c === '/' ? '_' : '-')
    .replace(/=+$/, '') + '=='
}

const STYLES = {
  cloudflare1020: () => ({
    status: 403,
    body: `<!DOCTYPE html><html lang="en-US"><head><title>Access denied | Cloudflare</title>
<meta charset="UTF-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
<meta name="robots" content="noindex, nofollow"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<style>body{margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;background:#f5f5f5;color:#333}.wrap{max-width:980px;margin:48px auto;padding:32px}h1{font-size:24px;color:#d9534f}h2{font-size:16px;color:#666;font-weight:normal}.ray{font-family:monospace;color:#999;font-size:12px;margin-top:32px;padding-top:16px;border-top:1px solid #ddd}</style>
</head><body><div class="wrap"><h1>Access denied</h1><h2>Error code 1020</h2>
<p>You do not have access to this page. The site owner may have set restrictions that prevent you from accessing the site.</p>
<div class="ray">Cloudflare Ray ID: <strong>${randomHex(8)}</strong> &middot; Your IP: hidden &middot; Performance &amp; security by Cloudflare</div>
</div></body></html>`,
  }),

  awsCloudfront: () => ({
    status: 403,
    body: `<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><title>ERROR: The request could not be satisfied</title></head>
<body><h1>403 ERROR</h1><h2>The request could not be satisfied.</h2>
<p>The Amazon CloudFront distribution is configured to block access from your country.</p>
<hr noshade size="1px">
<address>Generated by cloudfront (CloudFront)<br>
Request ID: ${randomReqId()}</address>
</body></html>`,
  }),

  modSecurity: () => ({
    status: 403,
    body: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head>
<title>403 Forbidden</title></head><body><h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr><address>Apache/2.4.41 (Ubuntu) Server at example.com Port 443</address>
</body></html>`,
  }),

  generic403: () => ({
    status: 403,
    body: `<!DOCTYPE html><html><head><title>403 Forbidden</title></head>
<body><h1>403 Forbidden</h1><p>You do not have permission to access this resource.</p></body></html>`,
  }),

  fake500: () => ({
    status: 500,
    body: `<!DOCTYPE html><html><head><title>500 Internal Server Error</title></head>
<body><h1>500 Internal Server Error</h1><p>The server encountered an internal error and was unable to complete your request.</p></body></html>`,
  }),

  silent200: () => ({
    status: 200,
    body: `<!DOCTYPE html><html><head><title>Search results</title></head><body><main><p>No results found.</p></main></body></html>`,
  }),
}

export function renderBlockPage(style) {
  const fn = STYLES[style] || STYLES.generic403
  return fn()
}

export const ALL_STYLES = Object.keys(STYLES)
